### ISSUE TITLE
TypeError: Cannot read property 'replace' of undefined

### ISSUE THREAD

**Issue by jdimarzio** [tgreyjs/typedoc-plugin-markdown#14]
Receive the following error when running with this theme:

Using TypeScript 2.4.1 from C:\Users\jdimarzio\AppData\Roaming\npm\node_modules\typedoc\node_modules\typescript\lib
C:\Users\jdimarzio\AppData\Roaming\npm\node_modules\typedoc\dist\lib\models\reflections\abstract.js:173
            var alias = this.name.replace(/[^a-z0-9]/gi, '_').toLowerCase();
                                  ^

TypeError: Cannot read property 'replace' of undefined
    at ProjectReflection.Reflection.getAlias (C:\Users\jdimarzio\AppData\Roaming\npm\node_modules\typedoc\dist\lib\models\reflections\abstract.js:173:35)
    at Function.DefaultTheme.getUrl (C:\Users\jdimarzio\node_modules\typedoc\dist\lib\output\themes\DefaultTheme.js:196:30)
    at Function.DefaultTheme.getUrl (C:\Users\jdimarzio\node_modules\typedoc\dist\lib\output\themes\DefaultTheme.js:199:32)
    at Function.MarkdownTheme.buildUrls (C:\Users\jdimarzio\node_modules\typedoc-plugin-markdown\dist\theme\index.js:36:57)
    at C:\Users\jdimarzio\node_modules\typedoc-plugin-markdown\dist\theme\index.js:127:31
    at Array.forEach (<anonymous>)
    at MarkdownTheme.getUrls (C:\Users\jdimarzio\node_modules\typedoc-plugin-markdown\dist\theme\index.js:126:33)
    at Renderer.render (C:\Users\jdimarzio\AppData\Roaming\npm\node_modules\typedoc\dist\lib\output\renderer.js:45:34)
    at CliApplication.Application.generateDocs (C:\Users\jdimarzio\AppData\Roaming\npm\node_modules\typedoc\dist\lib\application.js:100:23)
    at CliApplication.bootstrap (C:\Users\jdimarzio\AppData\Roaming\npm\node_modules\typedoc\dist\lib\cli.js:62:26)

**Comment by tgreyuk** [comment]
It's a bit hard to replicate without further details but please try v1.0.12 as I have implemented the same logic as the default theme that might fix the issue. Let me know.. thanks.

**Comment by jdimarzio** [comment]
Still getting the same error.  Would love to get you more details, please advise on how to do so

**Comment by tgreyuk** [comment]
Ok that's a shame.  Are you using any other plugins or additional options? Details of tsconfig might be useful too. Thanks.

**Comment by jdimarzio** [comment]
Very generic usage-
typedoc --mode modules --out <outFolder> <inFolder> --theme markdown

I'm using VS2015 so there isn't really a tsconfig (that i'm aware of)

**Comment by geethika18** [comment]
I'm hitting the same issue. Could someone help me out with it?
